# Generated by Django 4.2 on 2024-01-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_borrowedbooks_bookdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='app.book'),
        ),
    ]
